//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Amount
{
	public virtual int Amount
	{
		get;
		set;
	}

	public virtual int List<PlayerBets>
	{
		get;
		set;
	}

	public virtual int SetPlayerBet()
	{
		throw new System.NotImplementedException();
	}

	public virtual int WinAmount()
	{
		throw new System.NotImplementedException();
	}

	public virtual int CheckAmount()
	{
		throw new System.NotImplementedException();
	}

	public virtual int LoseAmount()
	{
		throw new System.NotImplementedException();
	}

}

