//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Board
{
	public string showplayercard
	{
		get;
		set;
	}

	public int currentplayerbet
	{
		get;
		set;
	}

	public int value
	{
		get;
		set;
	}

	public string showdealercard
	{
		get;
		set;
	}

	public int currentamount
	{
		get;
		set;
	}

	public int ShowCurrentAmount()
	{
		
	}

	public int ShowCurrentBet()
	{
		
	}

	public string ShowPlayerCard()
	{
		
	}

	public string ShowDealerCard()
	{
		
	}

	public void AddCard(object Card, object Player1)
	{
		
	}

	public int TotalValue()
	{
		
	}

	public void ShowHiddencard(object Hand)
	{
		
	}

}

