//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Card
{
	public virtual string Value
	{
		get;
		set;
	}

	public virtual string Suit
	{
		get;
		set;
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

