//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Card
{
	public string Value
	{
		get;
		set;
	}

	public string Suit
	{
		get;
		set;
	}

	public string ToString()
	{
		
	}

}

