//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Deck
{
	public virtual string List<Card>
	{
		get;
		set;
	}

	public virtual random Random
	{
		get;
		set;
	}

	public virtual List<Card> GetTopCard()
	{
		throw new System.NotImplementedException();
	}

	public virtual random ShuffelCard()
	{
		throw new System.NotImplementedException();
	}

}

