//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Hand
{
    Card card = new Card();
    List<Hand>hand=new List<Hand>();

	public string List<Hand>
	{
		get;
		set;
	}

	public void AddCard(card)
	{
        hand.Add(card);
	}

}

