//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
    Amount amount = new Amount();
	public int bet
	{
		get;
		set;
	}

	public string hit
	{
		get;
		set;
	}

	public string stay
	{
		get;
		set;
	}

	public void MyBet()
	{
        bet = int.Parse(Console.ReadLine());
        while (bet > amount.MyAmount)
        {
            Console.WriteLine("Can't bet higher than your amount");
            break;
        }
	}

	public void RequestAction(object Hand, object Dealer visable hand)
	{
		
	}

}

