//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rules
{
	public virtual int draw
	{
		get;
		set;
	}

	public List<Hand> CheckValue()
	{
		
	}

	public int DealerMustDraw()
	{
		
	}

	public int EqualsLessFive()
	{
		
	}

	public int MaxFiveCards()
	{
		
	}

	public string CompareHands(object Hand, object Hand)
	{
		
	}

}

