//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rules
{
	public virtual int draw
	{
		get;
		set;
	}

	public virtual List<Hand> CheckValue()
	{
        CheckValue.

		throw new System.NotImplementedException();
	}

	public virtual int DealerMustDraw()
	{
		throw new System.NotImplementedException();
	}

	public virtual int EqualsLessFive()
	{
		throw new System.NotImplementedException();
	}

	public virtual int MaxFiveCards()
	{
		throw new System.NotImplementedException();
	}

	public virtual string CompareHands(object Hand, object Hand)
	{
		throw new System.NotImplementedException();
	}

}

